# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='活动名称')),
                ('picture', models.ImageField(upload_to='activity/%Y%m/%d', verbose_name='图片地址')),
                ('url', models.URLField(verbose_name='url地址')),
            ],
            options={
                'verbose_name': '首页活动管理',
                'verbose_name_plural': '首页活动管理',
            },
        ),
        migrations.CreateModel(
            name='ActivityGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '首页专区活动商品管理',
                'verbose_name_plural': '首页专区活动商品管理',
            },
        ),
        migrations.CreateModel(
            name='ActivityZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='活动专区名称')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('isAdded', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '活动专区管理',
                'verbose_name_plural': '活动专区管理',
            },
        ),
        migrations.CreateModel(
            name='LunBoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('picture', models.ImageField(upload_to='lunbo/%Y%m/%d', verbose_name='图片')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '轮播图管理',
                'verbose_name_plural': '轮播图管理',
                'db_table': 'lunbo',
            },
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='分类名')),
                ('intro', models.CharField(blank=True, max_length=255, null=True, verbose_name='分类简介')),
            ],
            options={
                'verbose_name': '商品分类管理',
                'verbose_name_plural': '商品分类管理',
                'db_table': 'ShopCategory',
            },
        ),
        migrations.CreateModel(
            name='ShopPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('url', models.ImageField(upload_to='shop_picture/%Y%m/%d', verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '商品相册',
                'verbose_name_plural': '商品相册',
                'db_table': 'shop_picture',
            },
        ),
        migrations.CreateModel(
            name='ShopSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('intro', models.CharField(blank=True, max_length=255, null=True, verbose_name='简介')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='价格')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('url', models.ImageField(upload_to='shop_sku/%Y%m/%d', verbose_name='LOGO地址')),
                ('isAdded', models.BooleanField(default=True, verbose_name='是否上架')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ShopCategory', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品SKU管理',
                'verbose_name_plural': '商品SKU管理',
                'db_table': 'ShopSku',
            },
        ),
        migrations.CreateModel(
            name='ShopSpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='详情')),
            ],
            options={
                'verbose_name': '商品SPU管理',
                'verbose_name_plural': '商品SPU管理',
                'db_table': 'ShopSpu',
            },
        ),
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='单位名（斤，箱）')),
            ],
            options={
                'verbose_name': '商品单位管理',
                'verbose_name_plural': '商品单位管理',
                'db_table': 'ShopUnit',
            },
        ),
        migrations.AddField(
            model_name='shopsku',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ShopSpu', verbose_name='商品SPU'),
        ),
        migrations.AddField(
            model_name='shopsku',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ShopUnit', verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='shoppicture',
            name='shop_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ShopSku', verbose_name='商品SKU'),
        ),
        migrations.AddField(
            model_name='lunbomodel',
            name='shop_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ShopSku', verbose_name='商品SKUID'),
        ),
        migrations.AddField(
            model_name='activitygoods',
            name='shop_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ShopSku', verbose_name='商品SKU_ID'),
        ),
        migrations.AddField(
            model_name='activitygoods',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ActivityZone', verbose_name='活动专区ID'),
        ),
    ]
