# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
        migrations.AlterModelTable(
            name='activitygoods',
            table='activity_goods',
        ),
        migrations.AlterModelTable(
            name='activityzone',
            table='activity_zone',
        ),
    ]
