# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_shopcategory_oreder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopspu',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='详情'),
        ),
    ]
